{
 "title": "Al-Adhan Player",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GetlatestPrayerTime Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adhan_player_GetLatestPrayerTimes_processing_seconds_count"
    }
   ]
  },
  {
   "title": "adhan player main loop",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adhan_player_loop_counter_total"
    }
   ]
  },
  {
   "title": "adhan Player while loop count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adhan_player_loop_counter_total"
    }
   ]
  },
  {
   "title": "Minutes to Prayers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(epoch_to_fajr) - time()", "legendFormat": "Fajr" },
    { "expr": "(epoch_to_duhr) - time()", "legendFormat": " Duhr" },
    { "expr": "(epoch_to_asr) - time()", "legendFormat": "Asr" },
    { "expr": "(epoch_to_maghrib) - time()", "legendFormat": "Maghrib" },
    { "expr": "(epoch_to_isha) - time()", "legendFormat": "Isha" }
   ]
  }
 ]
}