{
 "title": "Gitlab Runner",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "runner",
    "query": {
     "query": "label_values(gitlab_runner_version_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Runner Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gitlab_runner_version_info" }
   ]
  },
  {
   "title": "Pipelines running",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 0 },
   "repeat": "runner",
   "targets": [
    {
     "expr": "sum (gitlab_runner_jobs{job=~\"$runner\", state=\"running\"}) by (executor_stage)",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Pipelines pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 0 },
   "repeat": "runner",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_jobs{job=~\"$runner\", state=\"pending\"}",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Pipelines running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (gitlab_runner_jobs{job=~\"$runner\", state=\"running\"}) by (executor_stage)",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Pipelines pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gitlab_runner_jobs{job=~\"$runner\", state=\"pending\"}",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "API Request Statuses Total N",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gitlab_runner_api_request_statuses_total[10m])",
     "legendFormat": "{{job}} {{runner}}"
    }
   ]
  },
  {
   "title": "Errors Total N",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitlab_runner_errors_total", "legendFormat": "{{runner}} {{level}}" }
   ]
  },
  {
   "title": "Limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitlab_runner_limit", "legendFormat": "{{job}} {{runner}}" }
   ]
  },
  {
   "title": "Autoscaling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Autoscaling Machine Creation Duration in seconds (bucket)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket",
       "legendFormat": "{{job}} {{executor}}"
      }
     ]
    },
    {
     "title": "Autoscaling Machine Creation Duration in Seconds (sum)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gitlab_runner_autoscaling_machine_creation_duration_seconds_sum",
       "legendFormat": "{{job}} {{executor}}"
      }
     ]
    },
    {
     "title": "Autoscaling Machine Creation in seconds (count)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gitlab_runner_autoscaling_machine_creation_duration_seconds_count",
       "legendFormat": "{{job}} {{executor}}"
      }
     ]
    },
    {
     "title": "Autoscaling Machine States",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gitlab_runner_autoscaling_machine_states",
       "legendFormat": "{{job}} {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Concurrency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gitlab_runner_request_concurrency",
       "legendFormat": "{{job}} {{runner}}"
      }
     ]
    },
    {
     "title": "Concurrency Exceeded Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gitlab_runner_request_concurrency_exceeded_total",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Concurrent",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "gitlab_runner_concurrent", "legendFormat": "{{job}}" }
     ]
    }
   ]
  }
 ]
}